export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REGISTRY_START = 'REGISTRY_START';
export const REGISTRY_SUCCESS = 'REGISTRY_SUCCESS';
export const REGISTRY_ERROR = 'REGISTRY_ERROR';

export const CATEGORIES_START = 'CATEGORIES_START';
export const CATEGORIES_SUCCESS= 'CATEGORIES_SUCCESS';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';